# Generated by Django 5.0.6 on 2024-06-30 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='Task',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='Deadline',
        ),
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
