# Generated by Django 5.0.6 on 2024-07-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_todo_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='deadline',
            new_name='Deadline',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='task',
            new_name='Task',
        ),
    ]
